---

name: "Terraform Lint"

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Check Formatting"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/hashicorp/setup-terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # Validate formatting
      - name: Check Formatting
        id: fmt
        run: terraform fmt -check
        continue-on-error: false

...